In [ ]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

torch.set_default_device("cuda")

model = AutoModelForCausalLM.from_pretrained("microsoft/phi-1_5", torch_dtype="auto", trust_remote_code=True)
tokenizer = AutoTokenizer.from_pretrained("microsoft/phi-1_5", trust_remote_code=True)



In [ ]:
inputs = tokenizer('''Столица Америки?''', return_tensors="pt", return_attention_mask=False)

outputs = model.generate(**inputs, max_length=200)
text = tokenizer.batch_decode(outputs)[0]
print(text)

Столица Америки?

A:

You can use the following code:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a)

# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]

print(np.sum(a, axis=0))

# [12 15 18]

print(np.sum(a, axis=1))

# [ 6 15 24]

print(np.sum(a, axis=2))

# [12 15 18]

A:

You can use np.sum() with axis parameter.
import numpy as np

a = np.array([[1, 2, 3


In [ ]:
from transformers import pipeline, set_seed
generator = pipeline('text-generation', model='gpt2')
set_seed(42)
generator("The Capital of USA is ", max_length=30, num_return_sequences=5)


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'The Capital of USA is ___________ A________. A short-term money supply for a large market-based economy, under an elaborate system of'},
 {'generated_text': 'The Capital of USA is \xa0a huge capital for the University of California. What is most impressive is\xa0 the\xa0 ability of some of these campus'},
 {'generated_text': "The Capital of USA is ???? And there is no other place for those of us who know this story better than America's Capital of USA…\n"},
 {'generated_text': "The Capital of USA is \xa0familiarized with the world of the Big Oil.\nWith its history of leading the world's extraction of oil"},
 {'generated_text': 'The Capital of USA is \xa0an all-white nation of roughly 1.5 million people whose economic and cultural capital comes from a diverse range of'}]

In [ ]:
generator("To make pizza you need", max_length=30, num_return_sequences=5)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': "To make pizza you need a good pizza. That's why I'm working with the New York Pizza Kitchen and the New York Pizza Maker Project, to"},
 {'generated_text': 'To make pizza you need flour, or baking powder.\n\nIn 2 cups of a nonstick skillet, add the tomatoes and carrots. Cook until'},
 {'generated_text': 'To make pizza you need to get into a groove. That groove starts inside your head, and is the way you keep yourself centered, which makes it'},
 {'generated_text': 'To make pizza you need this in a bottle or in a container and you can fill everything up with a bit of whatever pie dough you want. The'},
 {'generated_text': "To make pizza you need to be able to make it from scratch – I can't tell if they all cook perfectly like this. The crust makes it"}]